### ISSUE TITLE
程序无法停止

### ISSUE THREAD

**Issue by lailoo** [renfliu/ucas#1]
师兄 ，程序运行后无法停止啊，
而且好像也登不上，就是我在服务器运行脚本后，从外网无法访问服务器

**Comment by renfliu** [comment]
你运行的那个命令无法停止？是login还是find？

**Comment by lailoo** [comment]
三个命令都无法停止，运行后也没什么反应，就卡在一直卡在命令行上，师兄，我明天去实验室给你看一下好不好，你明天去实验室吗？
